export const PRE_OPEN_CUSTOMER_DASHBOARD = true;

export const SHOW_CUSTOMER_WAIVER_PROMPTS = !PRE_OPEN_CUSTOMER_DASHBOARD;
export const SHOW_CUSTOMER_CROWD_STATUS = !PRE_OPEN_CUSTOMER_DASHBOARD;
export const SHOW_CUSTOMER_MEMBERSHIP = !PRE_OPEN_CUSTOMER_DASHBOARD;
export const SHOW_CUSTOMER_CLASS_BOOKING = !PRE_OPEN_CUSTOMER_DASHBOARD;
