import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

// Poppins 폰트 설정 (굵기 옵션 포함 가능)
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // 필요에 따라 조절 가능
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.variable}>
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}

